spring:
  liquibase:
    enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5332/postgres
    username: Alexander
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

resilience4j:
  timelimiter:
    instances:
      oneSecTimeLimiter:
        timeout-duration: 1s


